spring:
  # Data config
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/classicmodels?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 1234
